// Barrel for the parametrized Vinta template layouts.
//   import { Slide12, Slide35 } from "@/template";
// Each SlideNN is a prop-driven component whose defaults reproduce the
// official Vinta 2023 slide exactly. See CATALOG.md for per-slide props.
// (Not part of any deck — the /template registry globs NN.tsx only.)

export { default as Slide01 } from "./01";
export { default as Slide02 } from "./02";
export { default as Slide03 } from "./03";
export { default as Slide04 } from "./04";
export type { Slide04Meta,Slide04Props } from "./04";
export { default as Slide05 } from "./05";
export type { Slide05Meta,Slide05Props } from "./05";
export { default as Slide06 } from "./06";
export type { Slide06Props } from "./06";
export { default as Slide07 } from "./07";
export type { Slide07Meta,Slide07Props } from "./07";
export { default as Slide08 } from "./08";
export type { Slide08Props } from "./08";
export { default as Slide09 } from "./09";
export type { Slide09Props } from "./09";
export { default as Slide10 } from "./10";
export type { Slide10Props } from "./10";
export { default as Slide11 } from "./11";
export type { Slide11Feature,Slide11Props } from "./11";
export { default as Slide12 } from "./12";
export type { Slide12Stat,Slide12Props } from "./12";
export { default as Slide13 } from "./13";
export type { Slide13Stat,Slide13Props } from "./13";
export { default as Slide14 } from "./14";
export type { Slide14Item,Slide14Props } from "./14";
export { default as Slide15 } from "./15";
export type { Slide15Card,Slide15Props } from "./15";
export { default as Slide16 } from "./16";
export type { Slide16Props } from "./16";
export { default as Slide17 } from "./17";
export type { Slide17Card,Slide17Props } from "./17";
export { default as Slide18 } from "./18";
export type { Slide18Item,Slide18Props } from "./18";
export { default as Slide19 } from "./19";
export type { Slide19Item,Slide19Props } from "./19";
export { default as Slide20 } from "./20";
export type { Slide20Props } from "./20";
export { default as Slide21 } from "./21";
export type { Slide21Props } from "./21";
export { default as Slide22 } from "./22";
export type { Slide22Stat,Slide22Props } from "./22";
export { default as Slide23 } from "./23";
export type { Slide23Props } from "./23";
export { default as Slide24 } from "./24";
export type { Slide24Props } from "./24";
export { default as Slide25 } from "./25";
export type { Slide25Props } from "./25";
export { default as Slide26 } from "./26";
export type { Slide26Panel,Slide26Props } from "./26";
export { default as Slide27 } from "./27";
export type { Slide27Props } from "./27";
export { default as Slide28 } from "./28";
export type { Slide28Props } from "./28";
export { default as Slide29 } from "./29";
export type { Slide29Props } from "./29";
export { default as Slide30 } from "./30";
export type { Slide30Props } from "./30";
export { default as Slide31 } from "./31";
export type { Slide31Props } from "./31";
export { default as Slide32 } from "./32";
export type { Slide32Props } from "./32";
export { default as Slide33 } from "./33";
export type { Slide33Card,Slide33Props } from "./33";
export { default as Slide34 } from "./34";
export type { Slide34Props } from "./34";
export { default as Slide35 } from "./35";
export type { Slide35Props } from "./35";
export { default as Slide36 } from "./36";
export type { Slide36Props } from "./36";
export { default as Slide37 } from "./37";
export type { Slide37Props } from "./37";
export { default as Slide38 } from "./38";
export type { Slide38Props } from "./38";
export { default as Slide39 } from "./39";
export type { Slide39Props } from "./39";
export { default as Slide40 } from "./40";
export type { Slide40Props } from "./40";
export { default as Slide41 } from "./41";
export type { Slide41Props } from "./41";
export { default as Slide42 } from "./42";
export type { Slide42Person,Slide42Props } from "./42";
export { default as Slide43 } from "./43";
export type { Slide43Person,Slide43Props } from "./43";
export { default as Slide44 } from "./44";
export type { Slide44Person,Slide44Props } from "./44";
export { default as Slide45 } from "./45";
export type { Slide45Contact,Slide45Props } from "./45";
export { default as Slide46 } from "./46";
export type { Slide46Props } from "./46";
export { default as Slide47 } from "./47";
export type { Slide47Contact,Slide47Props } from "./47";
export { default as Slide48 } from "./48";
export type { Slide48Contact,Slide48Props } from "./48";
export { default as Slide49 } from "./49";
export type { Slide49Props } from "./49";
export { default as Slide50 } from "./50";
